### ISSUE TITLE
Пропуск объектов поставщика при проверках

### ISSUE THREAD

**Issue by unichkin** [1C-Company/ssl-support#38]
Вижу регистрацию ошибок в объектах поставщика БСП. Т.к. ошибки такого рода нет смысла править (поскольку БСП это внешняя обновляемая библиотека, на поддержке) хотелось бы, чтобы они не проверялись - нужна какая-то настройка. Желательно, чтобы она хранилась в гит-хранилище, а не воркспейсе.

**Comment by marmyshev** [comment]
Вроде же объекты на поддержке (на замке) не вообще не валидируются.
Настройки поддержки могут храниться в репе.

**Comment by marmyshev** [comment]
В версии 2021.2 будет новый механизм валидации, с возможностью подавления ошибок по настройкам.
